"""Add Reservation model

Revision ID: 21907fef09bf
Revises: 6a6c835a4a96
Create Date: 2025-01-22 14:17:40.088187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21907fef09bf'
down_revision: Union[str, None] = '6a6c835a4a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
