"""Change reservation dates to Date type

Revision ID: c1c5faa01e73
Revises: d137abc3243c
Create Date: 2025-01-22 17:32:33.976130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c5faa01e73'
down_revision: Union[str, None] = 'd137abc3243c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'IN_USE', 'COMPLETED', 'CANCELLED', name='reservationstatus'), nullable=False))
    op.alter_column('reservations', 'start_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('reservations', 'end_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_column('reservations', 'is_active')
    op.alter_column('users', 'position',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.Enum('STUDENT', 'PROFESSOR', 'RESEARCHER', 'STAFF', name='userposition'),
               existing_nullable=False,
               existing_server_default=sa.text("'STAFF'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'position',
               existing_type=sa.Enum('STUDENT', 'PROFESSOR', 'RESEARCHER', 'STAFF', name='userposition'),
               type_=sa.VARCHAR(length=22),
               existing_nullable=False,
               existing_server_default=sa.text("'STAFF'"))
    op.add_column('reservations', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.alter_column('reservations', 'end_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.alter_column('reservations', 'start_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.drop_column('reservations', 'status')
    # ### end Alembic commands ###
