"""add position column to users table

Revision ID: d137abc3243c
Revises: 3e16af2d9932
Create Date: 2024-03-19 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd137abc3243c'
down_revision: Union[str, None] = '3e16af2d9932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    position_enum = sa.Enum(
        'STAFF',                    # 사원
        'ASSISTANT_MANAGER',        # 대리
        'MANAGER',                  # 과장
        'DEPUTY_GENERAL_MANAGER',   # 차장
        'GENERAL_MANAGER',          # 부장
        'DIRECTOR',                 # 이사
        'MANAGING_DIRECTOR',        # 상무
        'EXECUTIVE_DIRECTOR',       # 전무
        'CEO',                      # 대표
        name='position'
    )
    position_enum.create(op.get_bind())
    op.add_column('users', sa.Column('position', position_enum, nullable=False, server_default='STAFF'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'position')
    position_enum = sa.Enum(name='position')
    position_enum.drop(op.get_bind())
    # ### end Alembic commands ###
